version: "3.1"
services:
    mysql:
      image: mysql:5.7
      container_name: wp-starter-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        MYSQL_DATABASE: "${DB_NAME}"
        MYSQL_USER: "${DB_USER}"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
      ports:
        - "${MYSQL_PORT}:3306"

    webserver:
      image: nginx:alpine
      container_name: wp-starter-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "${WEB_PORT}:80"

    php-fpm:
      build: docker/php-fpm
      container_name: wp-starter-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

